---
organizations:
  - name: opensearch-project
    projects:
      - name: 'OpenSearch Roadmap'
        number: 206
        fields:
          - name: 'Roadmap'
    repositories:
      - name: opensearch-api-specification
      - name: OpenSearch
      - name: opensearch-build-libraries
      - name: project-website
      - name: security
      - name: opensearch-spark
      - name: OpenSearch-Dashboards
      - name: data-prepper
      - name: ml-commons
      - name: opensearch-build
      - name: k-NN
      - name: documentation-website
      - name: security-analytics-dashboards-plugin
      - name: alerting
      - name: dashboards-maps
      - name: opensearch-learning-to-rank-base
      - name: opensearch-java
      - name: opensearch-dashboards-functional-test
      - name: cross-cluster-replication
      - name: opensearch-php
      - name: opensearch-py
      - name: dashboards-reporting
      - name: alerting-dashboards-plugin
      - name: notifications
      - name: opensearch-hadoop
      - name: opensearch-go
      - name: automation-app
      - name: dashboards-flow-framework
      - name: anomaly-detection
      - name: opensearch-testcontainers
      - name: opensearch-migrations
      - name: flow-framework
      - name: security-analytics
      - name: opensearch-cluster-cdk
      - name: opensearch-net
      - name: asynchronous-search
      - name: neural-search
      - name: dashboards-observability
      - name: opensearch-js
      - name: security-dashboards-plugin
      - name: spring-data-opensearch
      - name: foundation-website
      - name: dashboards-assistant
      - name: skills
      - name: opensearch-sdk-java
      - name: sql
      - name: opensearch-sdk-py
      - name: dashboards-search-relevance
      - name: opentelemetry-demo
      - name: oui
      - name: query-insights
      - name: custom-codecs
      - name: user-behavior-insights
      - name: project-meta
      - name: ml-commons-dashboards
      - name: opensearch-system-templates
      - name: anomaly-detection-dashboards-plugin
      - name: opensearch-benchmark-workloads
      - name: common-utils
      - name: sql-cli
      - name: .github
      - name: opensearch-benchmark
      - name: dashboards-query-workbench
      - name: dashboards-visualizations
      - name: observability
      - name: performance-analyzer
      - name: dashboards-notifications
      - name: reporting
      - name: index-management-dashboards-plugin
      - name: geospatial
      - name: opensearch-plugins
      - name: index-management
      - name: project-tools
      - name: skills-eval
      - name: opensearch-metrics
      - name: job-scheduler
      - name: opensearch-k8s-operator
      - name: terraform-provider-opensearch
      - name: opensearch-devops
      - name: helm-charts
      - name: dashboards-anywhere
      - name: ansible-playbook
      - name: maps
      - name: opensearch-ci
      - name: query-insights-dashboards
      - name: opensearch-catalog
      - name: performance-analyzer-rca
      - name: performance-analyzer-commons
      - name: opensearch-clients
      - name: reporting-cli
      - name: opensearch-rs
      - name: community
      - name: opensearch-oci-object-storage
      - name: opensearch-plugin-template-java
      - name: opensearch-py-ml
      - name: opensearch-ruby-aws-sigv4
      - name: data-prepper-documentation-website
      - name: search-processor
      - name: logstash-input-opensearch
      - name: logstash-output-opensearch
      - name: opensearch-ruby
      - name: project-website-search
      - name: opensearch-cli
      - name: oui-docs-cdk
      - name: sql-odbc
      - name: demos
      - name: opensearch-research
      - name: sql-jdbc
      - name: traffic-comparator
      - name: simple-schema
      - name: dashboards-desktop
      - name: perftop
      - name: opensearch-dashboards-test-library
      - name: dashboards-i18n
      - name: opensearch-dashboards-sdk-js
      - name: traffic-replayer
      - name: ux
      - name: piped-processing-language
      - name: technical-steering
      - name: opensearch-remote-metadata-sdk
      - name: opensearch-traffic-gateway
      - name: remote-vector-index-builder
      - name: opensearch-jvector
      - name: opensearch-protobufs
      - name: search-relevance
      - name: opensearch-mcp-server-py
