---
name: Hello World Operation

# You can listen to either `all` events or specific events
events:
  #  - all
  - issues.labeled
  - issues.assigned

tasks:
  - name: Print a message to the console
    call: print-to-console@default
    args:
      text: This is a sample output message!
  - name: Print a message to the console
    call: print-to-console@printToConsoleHelloWorld
  - call: create-issue-comment@createIssueCommentTagUser
    args:
      text: This comment is created by Hello World Operation
      tagUser: peterzhuamazon
